language: go
go:
  - "1.12.x"

sudo: required

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.24.1
  jobs:
    # TODO(js) Build per driver, not per db.
    # Builds with Go Modules enabled.
    # # - GO111MODULE=on DB=mssql 
    # # - GO111MODULE=on DB=mysql 
    # # - GO111MODULE=on DB=oracle 
    # # - GO111MODULE=on DB=postgres
    # # - GO111MODULE=on DB=sqlite
    # - GO111MODULE=on DB=mssql DRIVER=denisenkom_go-mssqldb
    # - GO111MODULE=on DB=mssql DRIVER=minus5_gofreetds
    # - GO111MODULE=on DB=mysql DRIVER=go-sql-driver_mysql
    # - GO111MODULE=on DB=mysql DRIVER=ziutek_mymysql
    # - GO111MODULE=on DB=oracle DRIVER=go-goracle_goracle
    # - GO111MODULE=on DB=oracle DRIVER=mattn_go-oci8
    # - GO111MODULE=on DB=oracle DRIVER=rana_ora
    - GO111MODULE=on DB=postgres DRIVER=jbarham_gopgsqldriver CGO_CFLAGS="-I/usr/include/postgresql"
    # - GO111MODULE=on DB=postgres DRIVER=jackc_pgx
    # - GO111MODULE=on DB=postgres DRIVER=lib_pq
    # - GO111MODULE=on DB=sqlite DRIVER=gwenn_gosqlite
    # - GO111MODULE=on DB=sqlite DRIVER=mattn_go-sqlite3
    # - GO111MODULE=on DB=sqlite DRIVER=mxk_go-sqlite
    # # Builds with Go Modules disabled.
    # # - GO111MODULE=off DB=mssql 
    # # - GO111MODULE=off DB=mysql 
    # # - GO111MODULE=off DB=oracle 
    # # - GO111MODULE=off DB=postgres
    # # - GO111MODULE=off DB=sqlite
    # - GO111MODULE=off DB=mssql DRIVER=denisenkom_go-mssqldb
    # - GO111MODULE=off DB=mssql DRIVER=minus5_gofreetds
    # - GO111MODULE=off DB=mysql DRIVER=go-sql-driver_mysql
    # - GO111MODULE=off DB=mysql DRIVER=ziutek_mymysql
    # - GO111MODULE=off DB=oracle DRIVER=go-goracle_goracle
    # - GO111MODULE=off DB=oracle DRIVER=mattn_go-oci8
    # - GO111MODULE=off DB=oracle DRIVER=rana_ora
    # - GO111MODULE=off DB=postgres DRIVER=jbarham_gopgsqldriver
    # - GO111MODULE=off DB=postgres DRIVER=jackc_pgx
    # - GO111MODULE=off DB=postgres DRIVER=lib_pq
    # - GO111MODULE=off DB=sqlite DRIVER=gwenn_gosqlite
    # - GO111MODULE=off DB=sqlite DRIVER=mattn_go-sqlite3
    # - GO111MODULE=off DB=sqlite DRIVER=mxk_go-sqlite

before_install:
  - sudo apt-get update
  # Update docker-compose.
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  # Install deps.
  # TODO(js) This driver does not currently build (github.com/jbarham/gopgsqldriver)
  # Setup for github.com/jbarham/gopgsqldriver
  - sudo apt-get install libpq-dev
  # Find the referenced header file
  # - find / -iname libpq-fe.h
  # Setup for github.com/minus5/gofreetds
  - sudo apt-get -y install freetds-dev
  # Go get our Go deps.
  - go get -v -t ./...

before_script:
  # - bash db-up.sh $DB 
  # # TODO(js) This sleep will probably prove to be flakey - it's an attempt to workaround slow VM startups.
  - bash db-up.sh $DB && sleep 1m

script:
  - go test -race && go test -race -p 1 ./drivers/$DB/$DRIVER
  # - go test -race && go test -p 1 ./drivers/$DB/...
  # - go test -race && ginkgo -r --randomizeAllSpecs --randomizeSuites ./drivers/$DB
  # - go test -race && go test -p 1 ./drivers/$DB/...
  # - go test -race && go test -p 1 -race -coverprofile=coverage.txt -covermode=atomic ./drivers/$DB/...
  # - go test -race -coverprofile=coverage.txt -covermode=atomic

after_script:
  - docker-compose down -v

# TODO(js) What is the best thing to do about coverage now we have a bazallion test?
# after_success:
#   - bash <(curl -s https://codecov.io/bash)

